"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-SuperRare',
 'project_name': 'Autonomous Brush Trader',
 'track': 'SuperRare',
 'pitch': 'A generative art pipeline that turns agent decisions, market states, and '
          'execution summaries into mintable media and auction plans.',
 'idea_titles': ['Trading Decisions as Art',
                 'Self-Minting Market Diary',
                 'Receipt-Bound Auction Agent'],
 'architecture_summary': 'A generative art pipeline turns agent decisions, market '
                         'states, and execution summaries into mintable media and '
                         'auction plans. The contract stores series metadata and '
                         'release policies while Python scripts render outputs and '
                         'draft the mint and auction sequence.',
 'overlap_targets': ['Uniswap Agentic Finance',
                     'ERC-8004 Receipts',
                     'Venice Private Agents',
                     'ENS',
                     'Bankr Gateway'],
 'primary_contract_name': 'AutonomousArtSeries',
 'primary_python_module': 'autonomous_brush',
 'category': 'art',
 'daily_budget_usd': 102,
 'per_action_budget_usd': 25,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'market_state',
                       'description': 'Market inputs and agent-decision traces for '
                                      'artwork.'},
                      {'name': 'media_plan',
                       'description': 'Frames, traits, and mint metadata.'},
                      {'name': 'auction_window',
                       'description': 'Bounded sale schedule and reserve policy.'},
                      {'name': 'receipts',
                       'description': 'Mint, auction, and verification receipts.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for AutonomousArtSeries.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'autonomous_brush.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'SuperRare',
               'docs_url': 'https://superrare.com/',
               'env_vars': ['SUPERRARE_API_KEY', 'SUPERRARE_MINT_URL'],
               'endpoint_env': 'SUPERRARE_MINT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Mint art-series media and auction metadata.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'}],
 'actions': [{'id': 'superrare_mint_series',
              'target': 'superrare',
              'purpose': 'Use SuperRare for a bounded action in this repo.',
              'partner': 'SuperRare',
              'action_kind': 'rest_json',
              'max_amount_usd': 40,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call SuperRare only after a dry-run artifact exists.',
                        'Use https://superrare.com/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 85,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 80,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 75,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
